Home page
alexandreohara/brainn-lp pull request #24
Opened 2020-09-21 19:01 UTC by alexandreohara

![home](https://user-images.githubusercontent.com/18475379/93809389-9873c400-fc23-11ea-9d1b-961aa1c341f1.gif)

2020-09-21 20:58 UTC, diogoshiroma requested changes

2020-09-21 20:58 UTC, diogoshiroma commented on src/Home.css
> +.column {
Essa column ainda ta sendo usada?

2020-09-21 20:58 UTC, diogoshiroma commented on src/Home.tsx
> +  color: white;
```suggestion
  color: ${Colors.white};
```

2020-09-21 20:58 UTC, diogoshiroma commented on src/Home.tsx
> +          <div className={'column'}>
Seria bom mudar isso pra Col do grid... se for deixar pra dps eh bom abrir uma issue pra n esquecermos

2020-09-21 20:58 UTC, diogoshiroma commented on src/Home.tsx
> +      <div style={{ padding: '64px' }}>
Bom tirar os styles ja q estamos usando o `styled components`

2020-09-21 20:58 UTC, diogoshiroma commented on src/components/Card.tsx
> +      background: linear-gradient(${props.deg}deg, ${props.startColor} 0%, ${props.endColor} 100%);
Aqui dps da pra mudarmos isso e passar direto o gradiente nesse componente né? Ao inves de passar as duas cores..

2020-09-21 20:58 UTC, diogoshiroma commented on src/components/Footer.tsx
> +    <div style={{ paddingLeft: '64px', background: '#072337' }}>
Mesmo esquema do style aqui.. bom extrair ja que estamos usando o styled components

2020-09-23 14:02 UTC, alexandreohara commented on src/components/Card.tsx
> +      background: linear-gradient(${props.deg}deg, ${props.startColor} 0%, ${props.endColor} 100%);
pode ser, mas acho que vou mudar em outro PR isso

2020-09-23 18:22 UTC, diogoshiroma approved these changes

2020-09-23 19:12 UTC, merged